### PR TITLE
Adding some tests for is_valid_signature

### PR DESCRIPTION
**Pull request by Gerson2102**
- [X] issue #113 
- [X] follows contribution [guide](https://github.com/keep-starknet-strange/starknet-phone/blob/main/CONTRIBUTING.md)
- [X] code change includes tests
- [ ] breaking change

This PR is adding some tests for the `is_valid_signature` function. Still work in progress.

### CODE REVIEW

**Comment by Gerson2102** [comment]
For the empty signature case. I'm getting this as a value when I run the test:

```
[FAIL] tests::test_account::test_empty_signature

Failure data:
    0x696e76616c6964207369676e6174757265 ('invalid signature')
```

And in the test I'm comparing the value to 'invalid signature' but it seems that is not catching it. I dont know how that works.

**Comment by Gerson2102** [comment]
The `test_is_not_valid_signature` is working fine. But I dont know how to do a test that checks that the signature is working fine. Or the function is working as expected. Is there any resource that could be shared with me to see how to do that?

**Comment by trbutler4** [comment]
> Contributor

thats fine

**Review by trbutler4 — APPROVED** [review]
thank you

**Pull request merged**
