### PR TITLE
refac: refactor wallet_app/android

### LINKED ISSUE #81: [feat] Refactor wallet_app/android
Right now, most of the "Activity" files in wallet_app/android are just in the main directory. We should refactor so that all activities are in the ui/activity folder.

### PR DESCRIPTION
**Pull request by Gift-Naomi**
resolves #81

### CODE REVIEW

**Comment by trbutler4** [comment]
There already is a ui directory at wallet_app/android/app/src/main/java/com/example/walletapp/

Just need to move the "Activity" files there, not the whole app.

**Review by trbutler4 — CHANGES_REQUESTED** [review]
just use the existing ui/activity directory

**Comment by Gift-Naomi** [comment]
@trbutler4 Hi sir, There's no existing ui/activity directory i created it.

**Comment by trbutler4** [comment]
> @trbutler4 Hi sir, There's no existing ui/activity directory i created it.

image

yes, there is. 

The path is: wallet_app/android/app/src/main/java/com/example/walletapp/ui/activity

**Pull request closed without merging**
