### PR TITLE
FEAT: Upgrade Cairo,Starknet Foundry and Openzeppelin dependencies

### PR DESCRIPTION
**Pull request by danielcdz**
## Summary
- [x] issue #112 
- [x] follows contribution [guide](https://github.com/keep-starknet-strange/starknet-phone/blob/main/CONTRIBUTING.md)
- [x] code change includes tests
- [x] breaking change

## Description
- This PR upgrades the contract version to `Cairo 2.8.4` and `starknet foundry 0.32.0`
- Upgrades `Openzeppelin dependencies to 0.18.0`
- Refactor tests to run with the new foundry version
- Refactor oz dependencies
- All tests are passing
- Contracts are compiled properly

## Screenshots
image

image

### CODE REVIEW

**Comment by trbutler4** [comment]
looks good! Can you resolve conflicts, and update code from other prs to work with latest version as well please?

**Comment by danielcdz** [comment]
@trbutler4 sure!

**Comment by danielcdz** [comment]
@trbutler4 Do you know what can be this error: 
image

**Comment by danielcdz** [comment]
@trbutler4 this is ready for review!

**Review by trbutler4 — APPROVED** [review]
Awesome! thank you

**Pull request merged**
